### ISSUE TITLE
Tests not working for play 2.4.x version of scaldi-play-example

### ISSUE THREAD

**Issue by ulejon** [scaldi/scaldi-play#14]
The test suite for https://github.com/OlegIlyenko/scaldi-play-example is not working. 
First of all it's not compiling. I fixed the compiling by enabling specs2 in build.sbt:

```
libraryDependencies ++= Seq(
  specs2,
  "com.typesafe.play" %% "play-cache" % "2.4.0-M3",
  "org.scaldi" %% "scaldi-play" % "0.5-play-2.4.0-M3-5"
)
```

I also had to replace WebModule with ServerModule in ApplicationSpec.scala.

When I got the tests to compile I tried to run them.
Got the following errors from ApplicationSpec:

```
info] Application should
[info] ! send 404 on a bad request
[error]    PlayException: : Unknown module type[Module [scaldi.play.ControllerInjector@6f6156b2] is not a Play module or a Guice module]  (GuiceInjectorBuilder.scala:205)
[error] play.api.inject.guice.GuiceableModule$.guiceable(GuiceInjectorBuilder.scala:205)
[error] play.api.inject.guice.GuiceableModule$$anonfun$loadModules$1.apply(GuiceInjectorBuilder.scala:196)
[error] play.api.inject.guice.GuiceableModule$$anonfun$loadModules$1.apply(GuiceInjectorBuilder.scala:196)
[error] play.api.inject.guice.GuiceableModule$.loadModules(GuiceInjectorBuilder.scala:196)
[error] play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:21)
[error] play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:21)
[error] play.api.inject.guice.GuiceApplicationBuilder.injector(GuiceApplicationBuilder.scala:75)
[error] play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:89)
[error] play.api.test.FakeApplication.<init>(Fakes.scala:220)
[error] test.ApplicationSpec$$anonfun$1$$anonfun$apply$3.apply(ApplicationSpec.scala:23)
[error] test.ApplicationSpec$$anonfun$1$$anonfun$apply$3.apply(ApplicationSpec.scala:23)
[info]
[info] ! render the index page
[error]    PlayException: : Unknown module type[Module [modules.UserModule@65fb8f5d] is not a Play module or a Guice module]  (GuiceInjectorBuilder.scala:205)
[error] play.api.inject.guice.GuiceableModule$.guiceable(GuiceInjectorBuilder.scala:205)
[error] play.api.inject.guice.GuiceableModule$$anonfun$loadModules$1.apply(GuiceInjectorBuilder.scala:196)
[error] play.api.inject.guice.GuiceableModule$$anonfun$loadModules$1.apply(GuiceInjectorBuilder.scala:196)
[error] play.api.inject.guice.GuiceableModule$.loadModules(GuiceInjectorBuilder.scala:196)
[error] play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:21)
[error] play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$8$1.apply(GuiceApplicationBuilder.scala:21)
[error] play.api.inject.guice.GuiceApplicationBuilder.injector(GuiceApplicationBuilder.scala:75)
[error] play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:89)
[error] play.api.test.FakeApplication.<init>(Fakes.scala:220)
[error] test.ApplicationSpec$$anonfun$1$$anonfun$apply$7.apply(ApplicationSpec.scala:41)
[error] test.ApplicationSpec$$anonfun$1$$anonfun$apply$7.apply(ApplicationSpec.scala:28)
```

I'm having issues running tests in my project that is using play 2.4.0-M3, so it would be much appreciated to have these tests working and to be able to learn from them.

**Comment by OlegIlyenko** [comment]
True, thanks for reminding me about this. Last time I was updating the
example application I noticed it, but then completely forgot to fix it.
Before M3 there was no clear way to do testing, but now it's more or less
clear. I will try to fix the tests later today. Meanwhile maybe you can
look in this test:

https://github.com/scaldi/scaldi-play/blob/play-2.4/src/test/scala/scaldi/play/ScaldiSupportTest.scala

The thing is - `FakeApication` is deprecated now AFAIK. So now you need to
use DI container to assemble "fake" application. Also you can look at the
official documentation here:

https://www.playframework.com/documentation/2.4.x/ScalaTestingWithGuice

It's for Guice, but scaldi-play provides very similar mechanism. just
replace Guice with Scaldi in class names and it should work as described.

**Comment by ulejon** [comment]
Thanx for feedback.

I'm trying to fix the test "render the index page" in ApplicationSpec. I have the following code:

```
"render the index page" in {
      class TestModule extends Module {
        bind [MessageService] when (inDevMode or inTestMode) to new MessageService {
          def getGreetMessage(name: String) = "Test Message"
        }
      }

      object TestGlobal extends GlobalSettings with ScaldiSupport {
        // test module will override `MessageService`
        def applicationModule = new TestModule :: new ServerModule :: new UserModule :: new ControllerInjector

        override def onStart(app: Application): Unit = {
          super.onStart(app)
        }
      }

      val application = new ScaldiApplicationBuilder().global(TestGlobal).build()

      running(application) {
        val home =  route(FakeRequest(GET, "/")).get

        status(home) must equalTo(OK)
        contentType(home) must beSome.which(_ == "text/html")

        println(contentAsString(home))

        contentAsString(home) must contain ("Test Message")
      }
    }
```

The test compiles and runs, but I get a test failure. In the Application controller the injected MessageService is still of type SimpleMessageService (and not the anonymous MessageService created in the TestModule).

However, if I remove the following entry from the application.conf file, the test succeeds:

```
play.modules.enabled += "modules.UserModule"
```

Any thoughts?

**Comment by OlegIlyenko** [comment]
I fixed the tests in the example application + provided some extra variations:

https://github.com/OlegIlyenko/scaldi-play-example/blob/master/test/ApplicationSpec.scala#L38

You need to avoid using `GlobalSetting` since it is now deprecated in play 2.4 and only there for backwards-compatibility purposes.

Along the way I also found a small bug which I fixed it in version **0.5-play-2.4.0-M3-6**. I think it was not working for you because of it.

**Comment by ulejon** [comment]
Excellent! Thank you very much

**Comment by ulejon** [comment]
I have an additional question regarding testing.
In Play 2.3.x I had a test that set up a fake application with a custom route like this:

val fakeApp = FakeApplication(withRoutes = {
            case ("POST", "/testurl") =>
                Action {
                    Ok("ok")
                }
        })

How would I do this using ScaldiApplicationBuilder?

**Comment by OlegIlyenko** [comment]
Unfortunately, `FakeApplication`, that comes with play out-of-the-box, is very Guice specific. It provides this convenience `withRoutes`, but in background it just overrides a default bindings for `Router`. 

I haven't implemented this convenience method for scaldi support yet, but it will definitely come out of the box later. Meanwhile, since play is now so nicely modularized, it's pretty easy to implement fake router like this:

```
class FakeRouter(fallback: Router)(fakeRoutes: PartialFunction[(String, String), Handler]) extends Router {
  val routes = new AbstractPartialFunction[RequestHeader, Handler] {
    override def applyOrElse[A <: RequestHeader, B >: Handler](rh: A, default: A => B) =
      fakeRoutes.applyOrElse((rh.method, rh.path), (_: (String, String)) => default(rh))
    def isDefinedAt(rh: RequestHeader) = fakeRoutes.isDefinedAt((rh.method, rh.path))
  } orElse new AbstractPartialFunction[RequestHeader, Handler] {
    override def applyOrElse[A <: RequestHeader, B >: Handler](rh: A, default: A => B) =
      fallback.routes.applyOrElse(rh, default)
    def isDefinedAt(x: RequestHeader) = fallback.routes.isDefinedAt(x)
  }

  def documentation = fallback.documentation
  def withPrefix(prefix: String) = new FakeRouter(fallback.withPrefix(prefix))(fakeRoutes)
}
```

Now you can use it to override the minding in new test module:

```
val fakeRotes = new Module {
  binding to new FakeRouter(inject[RoutesProvider].get)({
    case ("POST", "/testurl") => Action {
      Results.Ok("ok")
    }
  })
}
```

and then use this module to create an app:

```
withScaldiApp(modules = Seq(fakeRotes)) {
  val test =  route(FakeRequest(POST, "/testurl"))....
}
```

It's a lot of code for the end-user code, but it's all would be hidden in the library later.

Hope this helps

**Comment by ulejon** [comment]
Cool, thanx a lot! This will definitely help me!

**Comment by OlegIlyenko** [comment]
I just added `FakeRouterModule` in **0.5-play-2.4.0-RC1-8** to make fake routes creation easier. Not you can just do something like this:

      val fakeRotes = FakeRouterModule {
        case ("GET", "/some-url") => Action {
          Results.Ok("everything is fine")
        }
      }

      running(TestServer(3333, new ScaldiApplicationBuilder(modules = Seq(fakeRotes)).build()), HTMLUNIT) { browser =>
        browser.goTo("http://localhost:3333/some-url")

        browser.pageSource must contain("everything is fine")
      }
