### ISSUE TITLE
Build release for play 2.4.0

### ISSUE THREAD

**Issue by ulejon** [scaldi/scaldi-play#19]
Since Play 2.4.0 is officially released now, it would be nice with a final release for scaldi-play as well.

**Comment by OlegIlyenko** [comment]
Yep, time has come! :star2: 

I plan to release next stable version of scaldi-play with play 2.4.0 support until the end of the week

**Comment by OlegIlyenko** [comment]
While I still finalizing the release of scaldi-play for play 2.4.0, I just released version **0.5.6-RC1** which already built for Play 2.4.0.

**Comment by ulejon** [comment]
Nice! I will check it out

**Comment by OlegIlyenko** [comment]
Done :) https://groups.google.com/forum/#!topic/scaldi/_N0P4WSEASE

**Comment by ulejon** [comment]
Already using it :-) great work!
