### ISSUE TITLE
IllegalArgumentException when using default assets route from Play 2.4 template

### ISSUE THREAD

**Issue by DorianGrey** [scaldi/scaldi-play#22]
Hi,

I'm currently trying to move our Play 2.3 project to 2.4, using Scaldi for DI whereever possible. To get a little more in touch with it, I've tried to create a minimal basis, expanding it once it works.
I started with the basic play-scala template from the activator and added dependencies and structures according to the [scaldi-play-example](https://github.com/scaldi/scaldi-play-example), since the example itself did not work (not sure why, the error message was ... curious). Everything compiled fine, however, when I started the server and moved to the index page....

    java.lang.IllegalArgumentException: Type controllers.Assets does not have no-argument constructor or constructor with single implicit `Injector` argument.
     scaldi.play.ControllerInjector$$anonfun$5.apply(ControllerInjector.scala:70)
     scaldi.play.ControllerInjector$$anonfun$5.apply(ControllerInjector.scala:70)
     scala.Option.getOrElse(Option.scala:121)
    scaldi.play.ControllerInjector.scaldi$play$ControllerInjector$$createBinding(ControllerInjector.scala:70)
     scaldi.play.ControllerInjector$$anonfun$getBindingInternal$2$$anonfun$apply$2.apply(ControllerInjector.scala:33)
     scaldi.play.ControllerInjector$$anonfun$getBindingInternal$2$$anonfun$apply$2.apply(ControllerInjector.scala:32) [...]

The default route to this controller looks like this:

    GET     /assets/*file               controllers.Assets.versioned(path="/public", file: Asset)

I've also tried the version with a leading @:

    GET     /assets/*file               @controllers.Assets.versioned(path="/public", file: Asset)

But that lead to the same error, with an even longer stacktrace.

I've had a look at how this controller is defined, and surprisingly found to different definitions in play.api.controller.Assets.

    object Assets extends AssetsBuilder(LazyHttpErrorHandler) [L 234]

    @Singleton
    class Assets @Inject() (errorHandler: HttpErrorHandler) extends AssetsBuilder(errorHandler) [L 342]

It seems like the ControllerInjector gets confused about this - or is there something I did not recognize yet?

Might this be related to the more general Assets problem, like mentioned [here](https://github.com/playframework/playframework/issues/4576) ? I know it's about sub-projects, but there seems to be a more general issue with the assets route.

**Comment by OlegIlyenko** [comment]
Thanks for reporting this issue! I will look at it later today.

**Comment by OlegIlyenko** [comment]
There was a class loading issue during the app startup. I reported it here and also implemented a workaround in scaldi-play:

https://github.com/playframework/playframework/issues/4616

In my tests this cased all kinds of errors and I think it's possible that you faced many of them as well. There was also a minor issue with `ControllerInjector` which is fixed now too.

I just released version [0.5.7](https://github.com/scaldi/scaldi-play/releases/tag/v0.5.7) of scaldi-play with the bugfixes. It would be nice if you could check it in your application. 

If you still facing some problems, please feel free to reopen this issue or create the new one :)

**Comment by DorianGrey** [comment]
This particular problem is solved now, thank you!
