### ISSUE TITLE
Injection Works Correct in Development Mode, but Fails in Production

### ISSUE THREAD

**Issue by michaelahlers** [scaldi/scaldi-play#24]
In the process of migrating a Play 2.3 application to 2.4. Not sure if this is a Scaldi bug or a configuration problem in my project, but the behavior's simple. When in development mode (`sbt run`), everything works fine, but when in production (`sbt start`), I get Guice injection errors like the following.

```
[ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in controllers.Application. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Application.class(Application.scala:24)
  while locating controllers.Application

1 error]
```

For reference, that controller's definition is:

```scala
class Application(implicit inj: Injector)
  extends Controller
          with Injectable
          with LazyLogging {
  // ...
}
```

A line referencing that controller from `/conf/routes` is:

```
GET  /index  @controllers.Application.index
```

And, finally, a snippet from `/conf/application.conf`:

```
play.application.loader = scaldi.play.ScaldiApplicationLoader
play.modules.enabled += modules.ApplicationModule
play.modules.enabled += scaldi.play.ControllerInjector
```

Using `scaldi-play` version 0.5.8.

While I'm still trying to narrow this down or reproduce it in the Scadi sample Play application, I'm posting this bug early if there's a common mistake I'm making.

**Comment by OlegIlyenko** [comment]
hmmm.. I can't recognize this error from before. Since play tried to use Guice, I would assume, that it does not use `/conf/application.conf`. In particular `play.application.loader = scaldi.play.ScaldiApplicationLoader` property is unavailable in production mode for some reason. Maybe you can double check the config in production mode? Maybe you have some global/system configuration somewhere (e.g. .bashrc, etc.) where you override the config path?

**Comment by michaelahlers** [comment]
(Damn. I was hoping I was making an obvious mistake. :wink:) There's the rub; if I start [scaldi-play-example](https://github.com/scaldi/scaldi-play-example) with `sbt start`, it runs fine, whereas my application fails with the same method. The only meaningful difference I can identify now is my application is multi-module. Otherwise, they're configured the same. I'll keep poking and write back soon.

**Comment by michaelahlers** [comment]
Yikes; not at all a Scaldi bug. Sorry for the bad report!

**Comment by elmalto** [comment]
Hi @michaelahlers, I am running into the same issue. Do you have a solution for me?

**Comment by michaelahlers** [comment]
@elmalto, I'll try to get back to you with more detail, but as I recall this had something to do with errant SBT Native Packager settings that were no longer sensible for a Play 2.4 application. While a reasonable place to start looking that could be totally off base, so take it with [gain of salt](https://powerplantmen.files.wordpress.com/2014/12/cow-licking-salt-block.jpg).

**Comment by michaelahlers** [comment]
@elmalto, I've reviewed changelogs for my application's runtime `build.sbt`, and this _might_ be relevant to you:

```scala
// ...

javaOptions in Universal ++=
  // ...
  /* Commit message for this line was: causes the class loader to ignore the built-in application.conf with its defaults. */
  // s"-Dconfig.file=/etc/default/${packageName.value}" ::
  // ...
  Nil

/* In (or around) version 1.0.4, SBT Native Packager relocated--even for Java server applications on Linux--the external application configuration file to "application.ini" nested in the application home. Given a number of existing deployments, this needs to be preserved in a known location. See http://www.scala-sbt.org/sbt-native-packager/archetypes/cheatsheet.html?highlight=bashscriptconfiglocation#file-application-ini-or-etc-default for details. */
bashScriptConfigLocation := Some(s"/etc/default/${packageName.value}")

// ...
```

(Again, take all this with another gain of salt. I was rushing to fix this.) To recap: during development mode, `application.conf`—where your Scaldi modules are referenced—is correctly added to the classpath, but not when running with `start` (or, more correctly, [`testProd`](https://www.playframework.com/documentation/2.4.x/Production#Running-a-test-instance) and similar production-ready start scripts). In our original configuration, that `config.file` setting was live I vaguely recall it being the source of headaches when switching to Play 2.4.

**Comment by elmalto** [comment]
Thank you very much! I don't think I am using any extra settings, but maybe I missed it somewhere!

**Comment by michaelahlers** [comment]
Be sure to let me know if you make any progress. If you're still unlucky, try to distill your project down to essentials that exhibit this problem and I'll be happy to take a look!

**Comment by fabriziofortino** [comment]
@elmalto @michaelahlers Have you figured this out? I am stumbling in the same problem. Any idea?

**Comment by michaelahlers** [comment]
@fabriziofortino, see my comment from [October 15](https://github.com/scaldi/scaldi-play/issues/24#issuecomment-148425861). Generally-speaking, this was a classpath issue, caused by configuration differences between development and production modes.
