### ISSUE TITLE
Best way to inject Slick DB

### ISSUE THREAD

**Issue by guizmaii** [scaldi/scaldi-play#29]
Hi,

What's the best way to inject the default Slick DB ?

I know some possible options:

* Use the `play-slick` `HasDatabaseConfigProvider` trait (as recommended in the trait doc: https://github.com/playframework/play-slick/blob/master/src/core/src/main/scala/play/api/db/slick/DatabaseConfigProvider.scala#L147) :
```scala
class UserRepo(implicit inj: Injector) extends HasDatabaseConfigProvider[JdbcProfile] with Injectable {
  override protected val dbConfigProvider: DatabaseConfigProvider = inject[DatabaseConfigProvider]
  ...
}
```

* Use the `play-slick` `HasDatabaseConfig` trait (as saw here: https://github.com/scaldi/scaldi-play/blob/master/src/test/scala/scaldi/play/SlickTest.scala):
```scala
class UserRepo(implicit inj: Injector) extends HasDatabaseConfig[JdbcProfile] with Injectable {
  override protected val dbConfig: DatabaseConfig[JdbcProfile] = inject[DatabaseConfigProvider].get[JdbcProfile]
  ...
}
```

* Use the `play-slick` `HasDatabaseConfig` trait and a module:
```scala
class UserRepo(implicit inj: Injector) extends HasDatabaseConfig[JdbcProfile] with Injectable {
  override protected val dbConfig: DatabaseConfig[JdbcProfile] = inject[DatabaseConfig[JdbcProfile]]
  ...
}

// with:

class ApplicationModule extends Module {
  bind[DatabaseConfig[JdbcProfile]] to DatabaseConfigProvider.get[JdbcProfile](app = inject[Application])

  ...
}
```

* Other ? Use a provider ?

**Comment by guizmaii** [comment]
If I look to the example project: https://github.com/Mironor/play-slick-scaldi-silhouette-seed/blob/master/app/daos/SeedDAO.scala

It's the second solution that seems the most appropriate. Are you ok with this way ?

**Comment by guizmaii** [comment]
It seems that the only way that works in Play 2.5 is the second one:

```scala
class UserRepo(implicit inj: Injector) extends HasDatabaseConfig[JdbcProfile] with Injectable {
  override protected val dbConfig: DatabaseConfig[JdbcProfile] = inject[DatabaseConfigProvider].get[JdbcProfile]
  ...
}
```

I close the issue.

**Comment by OlegIlyenko** [comment]
Yeah, the second one looks good to me. The third one also looks clean, I think it should work as well.
