### ISSUE TITLE
CSRF-Token in 2.5

### ISSUE THREAD

**Issue by elmalto** [scaldi/scaldi-play#30]
I have upgraded to play 2.5 and am trying to test a POST request to the server, but I keep getting rejected: ```[trace] play.filters - [CSRF] Check failed because application/json request```

This is the relevant code:

```
class MyFilters(implicit inj:Injector) extends HttpFilters with Injectable {
  implicit val as = inject[ActorSystem]
  implicit val mat = ActorMaterializer()
  val gzip = new GzipFilter()
  val csrf = inject[CSRFFilter]
  def filters = Seq(gzip,csrf)
}
class FilterModule extends Module {
  binding to new MyFilters
}

lazy val toInject = new FilterModule

lazy implicit val inj: Injector = new ScaldiApplicationBuilder(modules = Seq(toInject))
    .configure(
      ("play.http.filters","filters.MyFilters"),
      ("play.filters.csrf.cookie.name","PLAY_CSRF_TOKEN")
    )
    .buildInj()

"Request" should {
    "use the correct language from Cookie" in {
      val request = FakeRequest(POST, "/posturl")
        .withJsonBody(Json.obj(...))
        .withHeaders("Accept-Language" -> "en-US")
        .withCookies(Cookie("useLang","de"),Cookie("PLAY_CSRF_TOKEN",Injectable.inject[CSRFAddToken].crypto.generateSignedToken))

      val Some(result) = route(app,request)
      status(result) mustEqual 200
    }
}
```

error message:

```
[info] - should use the correct language from Cookie *** FAILED ***
[info]   403 did not equal 200 (SearchSpec.scala:131)
```

Did I inject the CSRF properly? I used to use the Global object for CSRF, but it isn't available anymore.

**Comment by elmalto** [comment]
Sorry, I am still stuck here :( Should I be worried that every inject[] gives me a different Instance of CSRFFilter?

```
  lazy implicit val inj: Injector = new ScaldiApplicationBuilder(modules = Seq(toInject))
    .configure(
      ("play.http.filters","filters.MyFilters"),
      ("play.filters.csrf.cookie.name","PLAY_CSRF_TOKEN")
    )
    .buildInj()

  import scaldi.Injectable._

  println(s"Using 1 ${inject[CSRFFilter]}")
  println(s"Using 2 ${inject[CSRFFilter]}")
  println(s"Using 3 ${inject[CSRFFilter]}")
```
```
Using 1 play.filters.csrf.CSRFFilter@55486bb7
Using 2 play.filters.csrf.CSRFFilter@49a8afd7
Using 3 play.filters.csrf.CSRFFilter@33447a1f
```

**Comment by OlegIlyenko** [comment]
Sorry for such a late reply. I may be a bug in Play 2.5. I reported it here:

https://github.com/playframework/playframework/issues/6142

I also updated your code with the workaround:

```scala
class MyFilters(implicit inj:Injector) extends HttpFilters with Injectable {
  implicit val as = inject[ActorSystem]
  implicit val mat = ActorMaterializer()

  val gzip = inject [GzipFilter]
  val csrf = inject [CSRFFilter]

  def filters = Seq(gzip,csrf)
}

class FilterModule extends Module {
  binding to new MyFilters
}

def toInject = new FilterModule

val config = Configuration.from(Map(
  "play.filters.csrf.token.sign" → true,
  "play.filters.csrf.cookie.name" → "PLAY_CSRF_TOKEN"))

"Request" should {
  "use the correct language from Cookie" in {
    import Injectable._

    withScaldiInj(configuration = config, modules = Seq(toInject)) { implicit inj ⇒
      val app = inject [Application]
      val crypto = inject [CSRFTokenSigner]
      val token = crypto.generateSignedToken

      val request = FakeRequest("POST", "/posturl")
        .withHeaders("Accept-Language" → "en-US", "Csrf-Token" → token)
        .withCookies(Cookie("useLang", "de"), Cookie("PLAY_CSRF_TOKEN", token))
        .withBody(Json.obj("foo" → "bar"))

      val Some(result) = route(app, request)

      status(result) mustEqual 200
    }
  }
}
```

If you add a token via cookie **and** `Csrf-Token` header then test will pass.

**Comment by OlegIlyenko** [comment]
> Should I be worried that every inject[] gives me a different Instance of CSRFFilter?

No, it's normal. `CSRFFilter` is not configured as a singleton:

https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFFilter.scala#L24

**Comment by OlegIlyenko** [comment]
Turns out that the CSRF token need to be present 2 times in the request. So providing it via header and cookie looks like a valid approach: https://github.com/playframework/playframework/issues/6142#issuecomment-217506866

**Comment by elmalto** [comment]
Thank you! Will check it later today :)

**Comment by elmalto** [comment]
Perfect. It worked. Thank you!!

**Comment by gmethvin** [comment]
@elmalto Just to clarify, the cookie is used for storing the token generated by the server (by the CSRFFilter or CSRFAction) and this is checked against the token submitted by the user, either in the query string, body, or HTTP header. It needs to be present twice because it's comparing one value against the other.

Also you may want to check if you are affected by the [CSRF changes](https://www.playframework.com/documentation/2.5.x/Migration25#CSRF-changes) in 2.5.
