### ISSUE TITLE
deploy 0.5.16 (Scala 2.11) to maven central!

### ISSUE THREAD

**Issue by domdorn** [scaldi/scaldi-play#34]
Hi!
I just wanted to upgrade a play 2.5 project to play 2.6, but scaldi-play 0.5.16 (for scala 2.11!) is not yet published to maven central. For scala 2.12 it is published, but I can't migrate to that yet ( too many dependencies still are 2.11 only at the moment)

Thx!

**Comment by OlegIlyenko** [comment]
Ooops, sorry, completely forgot about 2.11. Just released new version that is cross-compiled to scala 2.11 & 2.12: https://github.com/scaldi/scaldi-play/releases/tag/v0.5.17

**Comment by domdorn** [comment]
thx!
